import { existsSync } from 'node:fs';
import { assertPersistentDatabase, config, env } from '../src/core/config.js';
import { commandDefinitions } from '../src/commands/definitions.js';
import { VERSION } from '../src/core/version.js';
console.log('GOAT • Local diagnostics');
console.log(`Version: ${VERSION}`);
console.log(`Node.js: ${process.version}`);
console.log(`Token: ${env.token && env.token !== 'PASTE_YOUR_BOT_TOKEN_HERE' ? 'Configured (hidden)' : 'Not configured — set DISCORD_TOKEN in Railway Variables or .env'}`);
console.log(`Database: ${env.databasePath}`);
assertPersistentDatabase();
if (process.env.RAILWAY_ENVIRONMENT_ID) console.log('Railway: database path is inside the attached volume');
console.log(`Guild: ${env.guildId ? 'Configured' : 'Auto-detection enabled'}`);
console.log(`Config: valid • timezone: ${config.timezone}`);
console.log('Ticket voting: manual Start Vote • 180s • first to 3 • majority at deadline, no quorum');
console.log('Logs: raw Gateway capture + durable snapshots; /message-logs status, test, retry');
console.log(`Message log destination: ${config.channels.messageLogs}`);
console.log(`Link filter: ${config.linkFilter.enabled ? 'enabled' : 'disabled'}; domains: ${config.linkFilter.allowedDomains.join(', ')}`);
console.log(`Approved GIFs: ${config.linkFilter.allowApprovedGifs ? 'everyone' : 'role exceptions only'}; providers: ${config.linkFilter.gifProviderDomains.join(', ')}`);
console.log(`Unrestricted GIF channels: ${config.linkFilter.unrestrictedGifChannelIds.join(', ')}`);
console.log(`Filter warnings: ${config.linkFilter.notifications.enabled ? 'enabled' : 'disabled'}; delete after ${config.linkFilter.notifications.deleteAfterSeconds}s`);
console.log(`New role username DMs: ${config.roleUsernameDm.enabled ? 'enabled' : 'disabled'}; initial holders are not notified`);
console.log(`Banner: ${existsSync('assets/goat-banner.png') ? 'OK' : 'MISSING'}`);
console.log(`Application example: ${existsSync('assets/application-mastery-example.png') ? 'OK' : 'MISSING'}`);
console.log(`Font: ${existsSync('assets/fonts/DejaVuSans-Bold.ttf') ? 'OK' : 'MISSING'}`);
console.log(`Commands: ${commandDefinitions.length} definitions validated`);
for (const c of commandDefinitions) c.toJSON();
console.log('Enable Server Members Intent and Message Content Intent in Developer Portal > Bot.');
console.log('Place the bot role above the clan/member roles it needs to rename or moderate.');
